export const programs = [
  {
    id: "gaza-aid",
    name: "For Our People in Gaza",
    slug: "gaza-aid",
    category: "Emergency Response",
    description: "Providing immediate humanitarian assistance to families affected by the crisis in Gaza",
    longDescription: "Under the \"For Our People in Gaza\" campaign, JHCO leads Jordan's response to the humanitarian crisis in the Gaza Strip: operating an air bridge from Marka Airport in Amman to Al-Arish, organizing regular land convoys of medical, food, and relief supplies, and implementing projects inside the Strip — food parcels and clean water, hot meals, hygiene kits, and bakeries distributing fresh bread to displaced communities — in coordination with official Palestinian authorities and local and international partners.",
    image: "/programs/gaza.jpg",
    impact: "15,000+ families supported",
    nameAr: "حملة «لأهلنا في غزة»",
    descriptionAr: "تقديم المساعدات الإنسانية العاجلة للأسر المتضررة من الأزمة في غزة",
    impactAr: "أكثر من 15,000 أسرة مدعومة",
    categoryAr: "الاستجابة الطارئة",
    longDescriptionAr: "في ظل الحصار المطبق على قطاع غزة وما يرافقه من أوضاع إنسانية قاسية، تواصل الهيئة جهودها ضمن حملة «لأهلنا في غزة»: تسيير جسر جوي إغاثي من مطار ماركا إلى مطار العريش، وتنظيم قوافل برية دورية محملة بالمساعدات الطبية والغذائية والإغاثية، وتنفيذ مشاريع داخل القطاع تشمل توزيع سلال غذائية ومياه نقية ووجبات ساخنة وطرود صحية، وإنشاء مخابز وتوزيع الخبز على الأسر النازحة — بالتنسيق مع الجهات الفلسطينية الرسمية والشركاء المحليين والدوليين.",
    photo: "/media/gaza-convoy.jpg",
    gallery: ["/media/gaza-meal-1.jpg", "/media/gaza-meal-2.jpg", "/media/gaza-water.jpg"],
    objectives: ["Deliver food, medicine, and shelter to crisis-affected families", "Sustain the Jordanian land and air aid bridge to Gaza", "Coordinate with international agencies for safe aid delivery"],
    objectivesAr: ["إيصال الغذاء والدواء والمأوى إلى الأسر المتضررة من الأزمة", "استدامة الجسر الأردني البري والجوي للمساعدات إلى غزة", "التنسيق مع الوكالات الدولية لإيصال المساعدات بأمان"],
    status: "Active",
    budget: "$2.5M",
  },
  {
    id: "amputees-gaza",
    name: "Restoring Hope — Supporting Amputees in Gaza",
    slug: "amputees-gaza",
    category: "Medical Support",
    description: "Prosthetic limbs, rehabilitation, and psychological support for amputees",
    longDescription: "Through the Jordanian \"Restoring Hope\" initiative, JHCO provides prosthetic limbs and essential medical care to those who lost limbs in the war on Gaza. The initiative works alongside the Royal Medical Services' Mobile Amputees Support Unit to give individuals a second chance at mobility, dignity, and an active role in their communities.",
    image: "/programs/amputees.jpg",
    impact: "850+ amputees supported",
    nameAr: "مبادرة استعادة الأمل — دعم مبتوري الأطراف في غزة",
    descriptionAr: "أطراف صناعية وتأهيل ودعم نفسي لمبتوري الأطراف",
    impactAr: "أكثر من 850 مستفيداً",
    categoryAr: "الدعم الطبي",
    longDescriptionAr: "في ظل الظروف الصعبة التي يعيشها أهلنا في غزة، يعاني كثيرون من فقدان أطرافهم نتيجة الصراع المستمر، وهم يستحقون فرصة جديدة للحياة. من خلال المبادرة الأردنية «استعادة الأمل»، نعمل على توفير الأطراف الصناعية والرعاية الطبية الضرورية لضحايا فقدان الأطراف في غزة، ومنحهم الأمل في استعادة حركتهم وقدرتهم على العمل والمساهمة في مجتمعهم.",
    photo: "/media/amputee-rehab.jpg",
    gallery: ["/media/amputee-rehab.jpg", "/media/amputee-relief.jpg"],
    objectives: ["Provide prosthetic limbs and assistive devices", "Deliver physiotherapy and rehabilitation services", "Offer psychological support for recovery and reintegration"],
    objectivesAr: ["توفير الأطراف الصناعية والأجهزة المساعدة", "تقديم خدمات العلاج الطبيعي والتأهيل", "تقديم الدعم النفسي للتعافي والاندماج"],
    status: "Active",
    budget: "$800K",
  },
  {
    id: "clothing-bank",
    name: "Charity Clothing Bank",
    slug: "clothing-bank",
    category: "Basic Needs",
    description: "Collecting and distributing clothing to families in need",
    longDescription: "Established in 2013, the Charity Clothes Bank provides appropriate clothing to families registered with the National Aid Fund across all governorates of the Kingdom. Through its exhibition in Al-Mahatta, families shop with dignity at no cost: each registered member receives a coupon for four pieces of clothing and a pair of shoes, plus household and toy items. The bank partners with over 300 local associations, and in a single year has distributed more than one million pieces to over 152,000 people, supported by more than 2,800 volunteers.",
    image: "/programs/clothing.jpg",
    impact: "1,000,000+ pieces distributed",
    nameAr: "بنك الملابس الخيري",
    descriptionAr: "جمع الملابس وتوزيعها على الأسر المحتاجة",
    impactAr: "أكثر من مليون قطعة موزعة",
    categoryAr: "الاحتياجات الأساسية",
    longDescriptionAr: "انطلق بنك الملابس الخيري مطلع تشرين الأول 2013 لتوفير الملابس الملائمة للأسر العفيفة في جميع محافظات المملكة وعلى مدار العام، عبر صالة عرض في منطقة المحطة وسط البلد تمنح الأسر متعة التسوق وانتقاء احتياجها بحرية تامة ودون مقابل. يتعاون البنك مع أكثر من 300 جمعية محلية شريكة للوصول إلى الأسر المحتاجة في المناطق والقرى النائية، ونجح في توزيع ما يقارب مليون قطعة استفاد منها أكثر من 152 ألف محتاج، بمساهمة أكثر من 2,800 متطوع. تحصل كل أسرة مسجلة على قسيمة: أربع قطع ملابس وزوج أحذية لكل فرد، وقطعة من المتفرقات وأخرى من الألعاب للعائلة.",
    photo: "",
    objectives: ["Collect and sort clothing donations to dignified standards", "Distribute seasonal clothing to vulnerable families", "Operate branch network and sorting centers across Jordan"],
    objectivesAr: ["جمع وفرز تبرعات الملابس وفق معايير تحفظ الكرامة", "توزيع الملابس الموسمية على الأسر المتعففة", "تشغيل شبكة الفروع ومراكز الفرز في أنحاء المملكة"],
    status: "Active",
    budget: "$200K",
  },
  {
    id: "tarabot",
    name: "Tarabot Project",
    slug: "tarabot",
    category: "Education & Development",
    description: "Educational and vocational training programs for youth",
    longDescription: "Tarabot Community Center, integrated in April 2015 in East Amman (Al-Mahatta) and funded by the Compassion Relief Tzu Chi Foundation, provides free services to all — adults and children of every nationality, with special focus on Syrian refugees. Its Psychosocial Support Department offers children's activities, homework help, informal education, and awareness sessions led by psychologists; its Training and Events Department builds life skills and financial literacy and hosts community events that strengthen social ties.",
    image: "/programs/tarabot.jpg",
    impact: "3,200+ youth trained",
    nameAr: "مشروع ترابط",
    descriptionAr: "برامج تعليمية وتدريب مهني للشباب",
    impactAr: "أكثر من 3,200 شاب مدرّب",
    categoryAr: "التعليم والتنمية",
    longDescriptionAr: "مركز ترابط المجتمعي، الذي انطلق في نيسان 2015 في شرق عمّان (المحطة) بتمويل من مؤسسة تسو تشي للإغاثة، يقدّم خدماته مجاناً للجميع — كباراً وأطفالاً من كل الجنسيات، مع تركيز خاص على اللاجئين السوريين. يوفّر قسم الدعم النفسي الاجتماعي أنشطة للأطفال ومساعدة في الواجبات وتعليماً غير نظامي وجلسات توعية بإشراف مختصين نفسيين، فيما يبني قسم التدريب والفعاليات المهارات الحياتية والثقافة المالية ويستضيف فعاليات مجتمعية تمتّن الروابط الاجتماعية.",
    photo: "",
    objectives: ["Run community centers with daily education and skills activities", "Build financial literacy and digital skills for youth and women", "Strengthen social cohesion through arts, sport, and reading programs"],
    objectivesAr: ["تشغيل مراكز مجتمعية بأنشطة تعليمية ومهارية يومية", "بناء الثقافة المالية والمهارات الرقمية للشباب والنساء", "تعزيز التماسك الاجتماعي عبر الفنون والرياضة والقراءة"],
    status: "Active",
    budget: "$600K",
  },
  {
    id: "arzaq",
    name: "Arzaq Project",
    slug: "arzaq",
    category: "Livelihood",
    description: "Supporting women entrepreneurs and small businesses",
    longDescription: "Arzaq empowers women through microfinance, business training, and market access to start and grow sustainable businesses.",
    image: "/programs/arzaq.jpg",
    impact: "1,500+ women entrepreneurs",
    nameAr: "مشروع أرزاق",
    descriptionAr: "دعم رائدات الأعمال والمشاريع الصغيرة",
    impactAr: "أكثر من 1,500 رائدة أعمال",
    categoryAr: "سبل العيش",
    longDescriptionAr: "يمكّن مشروع أرزاق النساء من خلال التمويل الأصغر والتدريب على الأعمال والوصول إلى الأسواق لبناء مشاريع مستدامة.",
    photo: "",
    objectives: ["Provide microfinance for women-led small businesses", "Deliver business and vocational training", "Open market access for home-based producers"],
    objectivesAr: ["توفير التمويل الأصغر للمشاريع الصغيرة التي تقودها نساء", "تقديم التدريب المهني وإدارة الأعمال", "فتح منافذ تسويقية للمنتجات المنزلية"],
    status: "Active",
    budget: "$500K",
  },
  {
    id: "tomaanah",
    name: "Tomaanah — Psychosocial Support",
    slug: "tomaanah",
    category: "Psychosocial Support",
    description: "Psychosocial support and gender-based violence awareness for adolescents, women, and men",
    longDescription: "Implemented by JHCO with support from Human Appeal, Tomaanah works toward a safer, more accepting society for all groups and nationalities by raising awareness of gender-based violence among adolescents, women, and men. The project runs specialized training curricula in psychosocial support, family counseling, and human rights: an interactive 8-session program for adolescents (12–17), sessions for adult women on understanding the roots of violence and building positive coping strategies, and a curriculum engaging adult men in rethinking concepts of power and gender roles.",
    image: "/programs/tomaanah.jpg",
    impact: "Supported by Human Appeal",
    nameAr: "مشروع طُمأنة — الدعم النفسي والإسناد الاجتماعي",
    descriptionAr: "دعم نفسي وإسناد اجتماعي وتوعية بالعنف القائم على النوع الاجتماعي لليافعين والنساء والرجال",
    impactAr: "بدعم من منظمة هيومن أبيل",
    categoryAr: "الدعم النفسي والاجتماعي",
    longDescriptionAr: "يُنفَّذ مشروع طُمأنة من قبل الهيئة بدعم من منظمة هيومن أبيل، ويهدف إلى بناء مجتمع أكثر أماناً وتقبّلاً لجميع الفئات والجنسيات، من خلال رفع الوعي حول العنف القائم على النوع الاجتماعي بين اليافعين واليافعات والنساء والرجال. يرتكز المشروع على برامج تدريبية متخصصة في الدعم النفسي والاجتماعي والإرشاد الأسري وحقوق الإنسان: دليل تفاعلي من 8 جلسات لليافعين (12–17 سنة)، وجلسات للنساء البالغات حول فهم جذور العنف وبناء استراتيجيات نفسية إيجابية، ومنهج يشرك الرجال في إعادة التفكير في مفاهيم السلطة والأدوار الجندرية.",
    photo: "",
    objectives: ["Raise psychosocial awareness of gender-based violence across all groups", "Empower participants to express emotions and face challenges in healthy, balanced ways", "Build critical thinking, problem-solving, and decision-making skills that foster mutual respect"],
    objectivesAr: ["تعزيز الوعي النفسي والاجتماعي حول العنف القائم على النوع الاجتماعي لدى جميع الفئات", "تمكين المشاركين من التعبير عن مشاعرهم والتعامل مع التحديات بأساليب صحية ومتوازنة", "بناء مهارات التفكير النقدي وحل المشكلات واتخاذ القرار بما يعزز التفاهم والاحترام"],
    status: "Active",
    budget: "$450K",
  },
  {
    id: "dhii",
    name: "Dhii Showroom",
    slug: "dhii",
    category: "Economic Empowerment",
    description: "A sustainable marketplace showcasing products by women, productive families, and artisans",
    longDescription: "The Dhii showroom supports the economic empowerment of women, productive families, and artisans from all governorates of the Kingdom by providing a sustainable market to display local products and connect them with buyers. The exhibition features handmade, heritage, and creative products made by women and youth who graduated from training and economic-empowerment programs — turning skills into sustainable income. Beyond sales, Dhii is a space for success stories and for promoting the culture of local production.",
    image: "/programs/dhii.jpg",
    impact: "Artisans from all governorates",
    nameAr: "صالة العرض «ضي»",
    descriptionAr: "سوق مستدام لعرض وتسويق منتجات النساء والأسر المنتجة والحرفيين",
    impactAr: "حرفيون من مختلف المحافظات",
    categoryAr: "التمكين الاقتصادي",
    longDescriptionAr: "أُطلقت صالة العرض «ضي» لدعم التمكين الاقتصادي للنساء والأسر المنتجة والحرفيين من مختلف محافظات المملكة، من خلال توفير سوق مستدام لعرض وتسويق المنتجات المحلية وربطها بالأسواق. يضم المعرض منتجات يدوية وتراثية وإبداعية تنتجها سيدات وشباب استفادوا من برامج التدريب والتمكين الاقتصادي، بما يحوّل المهارات إلى فرص دخل مستدامة. ولا يقتصر دور «ضي» على البيع، بل يشكّل مساحة لعرض قصص النجاح وتعزيز ثقافة الإنتاج المحلي.",
    photo: "/media/refugee-camp.jpg",
    objectives: ["Provide a sustainable marketplace for local handmade and heritage products", "Turn training-program skills into sustainable household income", "Promote the culture of local production and showcase success stories"],
    objectivesAr: ["توفير سوق مستدام للمنتجات اليدوية والتراثية المحلية", "تحويل مهارات برامج التدريب إلى دخل مستدام للأسر", "تعزيز ثقافة الإنتاج المحلي وإبراز قصص النجاح"],
    status: "Active",
    budget: "$700K",
  },
  {
    id: "harir-alghor",
    name: "Harir Al-Ghor — Green Economy",
    slug: "harir-alghor",
    category: "Green Economy",
    description: "Recycling agricultural waste into creative, eco-friendly handicrafts",
    longDescription: "One of Jordan's distinctive initiatives, Harir Al-Ghor recycles agricultural waste — including banana stems — into creative, environmentally friendly craft products. The project empowers beneficiaries through comprehensive training that begins with psychosocial support and life skills, followed by a specialized course in project management. Participants learn to use the materials around them as a sustainable source of income, opening new horizons of success and independence, with many success stories already emerging.",
    image: "",
    impact: "A green-economy model in the Jordan Valley",
    status: "Active",
    budget: "",
    nameAr: "مشروع حرير الغور للاقتصاد الأخضر",
    descriptionAr: "إعادة تدوير المخلفات الزراعية وتحويلها إلى منتجات حرفية إبداعية صديقة للبيئة",
    impactAr: "نموذج للاقتصاد الأخضر في وادي الأردن",
    categoryAr: "الاقتصاد الأخضر",
    longDescriptionAr: "يُعدّ من المشاريع النوعية في الأردن؛ مبادرة فريدة تهدف إلى إعادة تدوير المخلفات ومنها سيقان الموز، وتحويلها إلى منتجات حرفية إبداعية وصديقة للبيئة. يستهدف المشروع تمكين المستفيدين من خلال تدريبات شاملة تبدأ بالدعم النفسي وتدريبات المهارات الحياتية، تليها دورة تمكينية متخصصة في إدارة المشاريع، ليتعلم المشاركون استخدام المواد المحيطة بهم مصدراً مستداماً للدخل يفتح آفاقاً جديدة للنجاح والاستقلالية. ويشهد المشروع اليوم العديد من قصص النجاح.",
    photo: "",
    objectives: ["Recycle agricultural waste into eco-friendly craft products", "Train beneficiaries in life skills and project management", "Create sustainable income from locally available materials"],
    objectivesAr: ["إعادة تدوير المخلفات الزراعية إلى منتجات حرفية صديقة للبيئة", "تدريب المستفيدين على المهارات الحياتية وإدارة المشاريع", "خلق دخل مستدام من المواد المتوفرة محلياً"],
  },
  {
    id: "medical-response-details",
    name: "Emergency Medical Response",
    slug: "medical-response-details",
    category: "Medical Support",
    description: "Rapid deployment of medical teams and mobile clinics to crisis zones",
    longDescription: "JHCO's Emergency Medical Response deploys trained medical teams within hours of crisis notification. Our mobile clinics provide trauma care, emergency medicine, disease prevention, and reproductive health services. With partnerships across 12 countries, we have treated over 200,000 patients in the past two years.",
    image: "",
    impact: "200,000+ patients served",
    nameAr: "الاستجابة الطبية الطارئة",
    descriptionAr: "نشر سريع لفرق طبية وعيادات متنقلة في مناطق الأزمات",
    impactAr: "أكثر من 200,000 مريض تم علاجهم",
    categoryAr: "الدعم الطبي",
    longDescriptionAr: "تنشر الاستجابة الطبية الطارئة التابعة للهيئة فرق طبية مدربة في غضون ساعات من إخطار الأزمة. تقدّم عياداتنا المتنقلة رعاية الصدمات والطب الطارئ والوقاية من الأمراض وخدمات الصحة الإنجابية.",
    photo: "",
    gallery: [],
    objectives: ["Deploy medical teams within critical first hours", "Provide comprehensive trauma and emergency care", "Build capacity of local health systems"],
    objectivesAr: ["نشر فرق طبية في الساعات الأولى الحرجة", "توفير رعاية صدمات شاملة وطارئة", "بناء قدرات الأنظمة الصحية المحلية"],
    status: "Active",
    budget: "$3.2M",
  },
  {
    id: "education-details",
    name: "Comprehensive Education Programs",
    slug: "education-details",
    category: "Education & Development",
    description: "Formal schooling, vocational training, and informal education for all ages",
    longDescription: "JHCO's education initiatives span from early childhood through adult learning. We operate 15 learning centers across three countries, train 8,500 students annually, and support 340 scholarship recipients.",
    image: "",
    impact: "8,500+ students trained",
    nameAr: "برامج التعليم الشاملة",
    descriptionAr: "التعليم النظامي والتدريب المهني والتعليم غير النظامي لجميع الأعمار",
    impactAr: "أكثر من 8,500 طالب مدرّب",
    categoryAr: "التعليم والتنمية",
    longDescriptionAr: "تشمل مبادرات التعليم التابعة للهيئة من الطفولة المبكرة إلى التعلم البالغ. نشغّل 15 مركز تعلم عبر ثلاث دول، ودرّب 8,500 طالب سنوياً.",
    photo: "",
    gallery: [],
    objectives: ["Increase school enrollment and attendance in vulnerable communities", "Integrate digital literacy across all age groups", "Provide teacher training and curriculum development"],
    objectivesAr: ["زيادة التحاق الطلاب بالمدارس والحضور في المجتمعات الضعيفة", "دمج الثقافة الرقمية عبر جميع الفئات العمرية", "توفير تدريب المعلمين وتطوير المناهج"],
    status: "Active",
    budget: "$2.8M",
  },
  {
    id: "livelihood-details",
    name: "Sustainable Livelihood Development",
    slug: "livelihood-details",
    category: "Livelihood",
    description: "Vocational training, microfinance, and market linkage programs",
    longDescription: "JHCO's livelihood programs create economic pathways for 2,400+ beneficiaries annually. We combine skills training with microfinance and business mentoring.",
    image: "",
    impact: "2,400+ employed annually",
    nameAr: "تنمية سبل العيش المستدامة",
    descriptionAr: "برامج التدريب المهني والتمويل الأصغر وربط الأسواق",
    impactAr: "أكثر من 2,400 موظفاً سنوياً",
    categoryAr: "سبل العيش",
    longDescriptionAr: "تنشئ برامج سبل العيش التابعة للهيئة مسارات اقتصادية لـ 2,400+ مستفيد سنوياً. نجمع بين تدريب المهارات والتمويل الأصغر والإرشاد على الأعمال.",
    photo: "",
    gallery: [],
    objectives: ["Train 2,000+ beneficiaries in income-generating skills", "Provide microfinance access with 95% loan repayment rates", "Link producers to sustainable markets"],
    objectivesAr: ["تدريب 2,000+ مستفيد على مهارات إدرار الدخل", "توفير الوصول للتمويل الأصغر برسوم سداد قروض 95٪", "ربط المنتجين بأسواق مستدامة"],
    status: "Active",
    budget: "$2.2M",
  },
  {
    id: "shelter-details",
    name: "Dignified Housing & Shelter",
    slug: "shelter-details",
    category: "Basic Needs",
    description: "Emergency shelter, transitional housing, and permanent housing solutions",
    longDescription: "From emergency tents to permanent housing, JHCO provides shelter solutions for 5,000+ families annually. Our housing programs include emergency response, transitional housing with services, and permanent reconstruction.",
    image: "",
    impact: "5,000+ families housed",
    nameAr: "المسكن الكريم والمأوى",
    descriptionAr: "المأوى الطارئ والإسكان الانتقالي وحلول الإسكان الدائم",
    impactAr: "أكثر من 5,000 أسرة مأمونة",
    categoryAr: "الاحتياجات الأساسية",
    longDescriptionAr: "من خيام الطوارئ إلى الإسكان الدائم، توفر الهيئة حلول المأوى لـ 5,000+ أسرة سنوياً. تشمل برامج الإسكان لدينا الاستجابة الطارئة والإسكان الانتقالي مع الخدمات.",
    photo: "",
    gallery: [],
    objectives: ["Provide immediate shelter in emergency contexts", "Build transitional housing with basic services", "Construct permanent homes with community participation"],
    objectivesAr: ["توفير مأوى فوري في السياقات الطارئة", "بناء إسكان انتقالي مع خدمات أساسية", "بناء منازل دائمة مع مشاركة المجتمع"],
    status: "Active",
    budget: "$4.1M",
  },
  {
    id: "food-security-details",
    name: "Food Security & Nutrition",
    slug: "food-security-details",
    category: "Basic Needs",
    description: "Food assistance, nutrition programs, and agricultural support",
    longDescription: "JHCO ensures food security for 8,000 families through monthly food baskets, community kitchens, and nutrition programs. We support smallholder farmers with inputs and training.",
    image: "",
    impact: "8,000 families fed monthly",
    nameAr: "الأمن الغذائي والتغذية",
    descriptionAr: "المساعدات الغذائية وبرامج التغذية ودعم المحاصيل",
    impactAr: "8,000 أسرة مطعومة شهرياً",
    categoryAr: "الاحتياجات الأساسية",
    longDescriptionAr: "تضمن الهيئة الأمن الغذائي لـ 8,000 أسرة من خلال سلال الطعام الشهرية والمطابخ المجتمعية وبرامج التغذية. ندعم المزارعين الصغار بالمدخلات والتدريب.",
    photo: "",
    gallery: [],
    objectives: ["Distribute food baskets to 8,000 vulnerable families", "Support smallholder agriculture development", "Promote nutrition awareness and healthy diets"],
    objectivesAr: ["توزيع سلال الطعام على 8,000 أسرة ضعيفة", "دعم تطوير الزراعة الصغيرة", "تعزيز الوعي بالتغذية والنظام الغذائي الصحي"],
    status: "Active",
    budget: "$2.5M",
  },
  {
    id: "mental-health-details",
    name: "Psychosocial Support & Mental Health",
    slug: "mental-health-details",
    category: "Psychosocial Support",
    description: "Trauma counseling, mental health services, and emotional resilience building",
    longDescription: "JHCO's mental health program serves 3,500+ individuals annually through individual counseling, group therapy, and community awareness.",
    image: "",
    impact: "3,500+ individuals served",
    nameAr: "الدعم النفسي والصحة العقلية",
    descriptionAr: "الاستشارات الصدمية وخدمات الصحة العقلية وبناء الصمود العاطفي",
    impactAr: "أكثر من 3,500 فرد مخدوم",
    categoryAr: "الدعم النفسي والاجتماعي",
    longDescriptionAr: "يخدم برنامج الصحة العقلية التابع للهيئة أكثر من 3,500 فرد سنوياً من خلال الاستشارات الفردية والعلاج الجماعي والتوعية المجتمعية.",
    photo: "",
    gallery: [],
    objectives: ["Provide counseling for trauma survivors", "Train community mental health workers", "Integrate mental health into primary healthcare"],
    objectivesAr: ["توفير الاستشارات لناجي الصدمات", "تدريب عاملي الصحة العقلية المجتمعيين", "دمج الصحة العقلية في الرعاية الأولية"],
    status: "Active",
    budget: "$1.8M",
  },
  {
    id: "water-sanitation-details",
    name: "Water, Sanitation & Hygiene",
    slug: "water-sanitation-details",
    category: "Basic Needs",
    description: "WASH infrastructure, hygiene education, and water systems",
    longDescription: "JHCO provides clean water and sanitation solutions to 20,000+ people. We drill wells, install water systems, and construct latrines with hygiene education.",
    image: "",
    impact: "20,000+ people with access",
    nameAr: "المياه والصرف الصحي والنظافة",
    descriptionAr: "البنية التحتية للصحة البيئية والتثقيف الصحي وأنظمة المياه",
    impactAr: "أكثر من 20,000 شخص لديهم وصول",
    categoryAr: "الاحتياجات الأساسية",
    longDescriptionAr: "توفر الهيئة حلول المياه النظيفة والصرف الصحي لـ 20,000+ شخص. نحفر الآبار، ونثبت أنظمة المياه، وننشئ المراحيض مع التثقيف الصحي.",
    photo: "",
    gallery: [],
    objectives: ["Drill 50 water wells annually", "Install piped water systems in 10 communities", "Construct gender-segregated sanitation facilities"],
    objectivesAr: ["حفر 50 بئر ماء سنوياً", "تثبيت أنظمة مياه مأنبورة في 10 مجتمعات", "بناء منشآت صرف صحي منفصلة حسب النوع"],
    status: "Active",
    budget: "$1.9M",
  },
  {
    id: "emergency-response-details",
    name: "Rapid Emergency Response",
    slug: "emergency-response-details",
    category: "Emergency Response",
    description: "Immediate crisis response, logistics coordination, and rapid needs assessment",
    longDescription: "JHCO's emergency response team mobilizes within hours. We provide immediate assistance and conduct rapid needs assessments to prioritize assistance.",
    image: "",
    impact: "Crisis response within 24-72 hours",
    nameAr: "الاستجابة الطارئة السريعة",
    descriptionAr: "استجابة الأزمات الفورية وتنسيق الخدمات اللوجستية وتقييم الاحتياجات السريع",
    impactAr: "استجابة الأزمة في غضون 24-72 ساعة",
    categoryAr: "الاستجابة الطارئة",
    longDescriptionAr: "يتحرك فريق الاستجابة الطارئة التابع للهيئة في غضون ساعات. نوفر مساعدة فورية ونجري تقييمات احتياجات سريعة لتحديد أولويات المساعدة.",
    photo: "",
    gallery: [],
    objectives: ["Mobilize response within 24 hours of crisis", "Provide immediate life-saving assistance", "Conduct needs assessments within 72 hours"],
    objectivesAr: ["تعبئة الاستجابة في غضون 24 ساعة من الأزمة", "توفير مساعدة فورية لإنقاذ الأرواح", "إجراء تقييمات احتياجات في غضون 72 ساعة"],
    status: "Active",
    budget: "$2.9M",
  },
  {
    id: "orphan-support-details",
    name: "Orphan Care & Support",
    slug: "orphan-support-details",
    category: "Child Protection",
    description: "Housing, education, healthcare, and mentorship for orphaned children",
    longDescription: "JHCO provides comprehensive support to 1,200+ orphaned children. Services include safe housing, quality education, healthcare, vocational training, and mentorship.",
    image: "",
    impact: "1,200+ orphans supported",
    nameAr: "دعم ورعاية الأيتام",
    descriptionAr: "الإسكان والتعليم والرعاية الصحية والإرشاد للأطفال الأيتام",
    impactAr: "أكثر من 1,200 يتيم مدعوم",
    categoryAr: "حماية الطفل",
    longDescriptionAr: "توفر الهيئة دعماً شاملاً لـ 1,200+ طفل يتيم. تتضمن الخدمات إسكاناً آمناً وتعليماً جيداً ورعاية صحية وتدريباً مهنياً وإرشاداً.",
    photo: "",
    gallery: [],
    objectives: ["Provide family-based care for 1,200 orphans", "Ensure education through secondary school", "Provide vocational training for youth"],
    objectivesAr: ["توفير رعاية قائمة على الأسرة لـ 1,200 يتيم", "ضمان التعليم حتى المدرسة الثانوية", "توفير التدريب المهني للشباب"],
    status: "Active",
    budget: "$2.1M",
  },
  {
    id: "disability-support-details",
    name: "Disability Support & Inclusion",
    slug: "disability-support-details",
    category: "Health & Rehabilitation",
    description: "Rehabilitation services, assistive devices, and inclusive community programs",
    longDescription: "JHCO supports 800+ people with disabilities through rehabilitation, assistive technology, skills training, and community integration programs.",
    image: "",
    impact: "800+ people with disabilities",
    nameAr: "دعم الإعاقة والإدراج",
    descriptionAr: "خدمات إعادة التأهيل والأجهزة المساعدة وبرامج المجتمع الشاملة",
    impactAr: "أكثر من 800 شخص من ذوي الإعاقة",
    categoryAr: "الصحة وإعادة التأهيل",
    longDescriptionAr: "تدعم الهيئة أكثر من 800 شخص من ذوي الإعاقة من خلال إعادة التأهيل والتكنولوجيا المساعدة وتدريب المهارات وبرامج الاندماج المجتمعي.",
    photo: "",
    gallery: [],
    objectives: ["Provide rehabilitation services to people with disabilities", "Distribute assistive devices and mobility aids", "Build inclusive community programs"],
    objectivesAr: ["توفير خدمات إعادة التأهيل لذوي الإعاقة", "توزيع الأجهزة المساعدة وأجهزة الحركة", "بناء برامج مجتمعية شاملة"],
    status: "Active",
    budget: "$1.5M",
  },
  {
    id: "skills-training-details",
    name: "Technical & Skills Training",
    slug: "skills-training-details",
    category: "Education & Development",
    description: "Vocational training in construction, mechanics, digital skills, and trades",
    longDescription: "JHCO's skills training programs provide technical education to 1,800+ youth annually. Courses include construction, electrical work, plumbing, automotive repair, and digital skills.",
    image: "",
    impact: "1,800+ youth trained",
    nameAr: "التدريب التقني والمهارات",
    descriptionAr: "التدريب المهني في البناء والميكانيكا والمهارات الرقمية والمهن",
    impactAr: "أكثر من 1,800 شاب مدرّب",
    categoryAr: "التعليم والتنمية",
    longDescriptionAr: "توفر برامج التدريب على المهارات التابعة للهيئة التعليم التقني لـ 1,800+ شاب سنوياً. تتضمن الدورات البناء والعمل الكهربائي والسباكة وإصلاح السيارات والمهارات الرقمية.",
    photo: "",
    gallery: [],
    objectives: ["Train 1,800 youth in technical trades", "Achieve 85% job placement rate", "Develop partnerships with employers"],
    objectivesAr: ["تدريب 1,800 شاب على المهن التقنية", "تحقيق معدل توظيف 85٪", "تطوير الشراكات مع أصحاب العمل"],
    status: "Active",
    budget: "$1.7M",
  },
  {
    id: "microfinance-details",
    name: "Microfinance & Entrepreneurship",
    slug: "microfinance-details",
    category: "Economic Empowerment",
    description: "Small loans, business training, and enterprise development support",
    longDescription: "JHCO's microfinance program provides loans averaging 400-800 USD to 1,600+ entrepreneurs annually. Average loan repayment rate is 96%.",
    image: "",
    impact: "1,600+ entrepreneurs supported",
    nameAr: "التمويل الأصغر وريادة الأعمال",
    descriptionAr: "قروض صغيرة وتدريب الأعمال ودعم تطوير المشاريع",
    impactAr: "أكثر من 1,600 رائد أعمال مدعوم",
    categoryAr: "التمكين الاقتصادي",
    longDescriptionAr: "يوفر برنامج التمويل الأصغر التابع للهيئة قروضاً بمتوسط 400-800 دولار لـ 1,600+ رائد أعمال سنوياً. معدل سداد القروض بمتوسط 96٪.",
    photo: "",
    gallery: [],
    objectives: ["Provide 1,600 microloans annually", "Maintain 95%+ repayment rates", "Support business plan development"],
    objectivesAr: ["توفير 1,600 تمويل أصغر سنوياً", "الحفاظ على رسوم السداد 95٪+", "دعم تطوير خطة الأعمال"],
    status: "Active",
    budget: "$1.3M",
  },
  {
    id: "community-development-details",
    name: "Community Development & Resilience",
    slug: "community-development-details",
    category: "Community Development",
    description: "Community centers, social cohesion programs, and collective initiatives",
    longDescription: "JHCO operates 18 community centers serving 25,000+ people. Programs build social cohesion, leadership, civic engagement, and collective problem-solving.",
    image: "",
    impact: "25,000+ people engaged",
    nameAr: "تنمية المجتمع والصمود",
    descriptionAr: "مراكز المجتمع وبرامج التماسك الاجتماعي والمبادرات الجماعية",
    impactAr: "أكثر من 25,000 شخص منخرط",
    categoryAr: "تنمية المجتمع",
    longDescriptionAr: "تشغّل الهيئة 18 مركز مجتمع يخدم 25,000+ شخص. تبني البرامج التماسك الاجتماعي والقيادة والمشاركة المدنية وحل المشاكل الجماعي.",
    photo: "",
    gallery: [],
    objectives: ["Operate 18 active community centers", "Serve 25,000+ community members", "Build leadership and civic capacity"],
    objectivesAr: ["تشغيل 18 مركز مجتمع نشط", "خدمة 25,000+ من أعضاء المجتمع", "بناء القيادة والقدرة المدنية"],
    status: "Active",
    budget: "$2.3M",
  },
  {
    id: "women-support-details",
    name: "Women Empowerment & Protection",
    slug: "women-support-details",
    category: "Gender & Social Protection",
    description: "Women's leadership, economic empowerment, and violence prevention",
    longDescription: "JHCO's women empowerment program reaches 2,500+ women through leadership training, economic skills, and protection services.",
    image: "",
    impact: "2,500+ women empowered",
    nameAr: "تمكين المرأة والحماية",
    descriptionAr: "قيادة النساء والتمكين الاقتصادي والوقاية من العنف",
    impactAr: "أكثر من 2,500 امرأة مُمكّنة",
    categoryAr: "النوع الاجتماعي والحماية الاجتماعية",
    longDescriptionAr: "يصل برنامج تمكين المرأة التابع للهيئة إلى 2,500+ امرأة من خلال تدريب القيادة والمهارات الاقتصادية وخدمات الحماية.",
    photo: "",
    gallery: [],
    objectives: ["Train 2,500 women in leadership", "Provide economic empowerment programs", "Combat gender-based violence"],
    objectivesAr: ["تدريب 2,500 امرأة على القيادة", "توفير برامج التمكين الاقتصادي", "محاربة العنف القائم على النوع الاجتماعي"],
    status: "Active",
    budget: "$1.9M",
  },
  {
    id: "youth-employment-details",
    name: "Youth Employment & Engagement",
    slug: "youth-employment-details",
    category: "Economic Empowerment",
    description: "Job training, employment linkage, and youth leadership development",
    longDescription: "JHCO engages 2,100+ youth annually through employment training, internships, and leadership programs. We partner with employers to place graduates in quality jobs.",
    image: "",
    impact: "2,100+ youth employed",
    nameAr: "التوظيف والتشغيل الشبابي",
    descriptionAr: "تدريب التوظيف وربط التوظيف وتطوير قيادة الشباب",
    impactAr: "أكثر من 2,100 شاب موظفاً",
    categoryAr: "التمكين الاقتصادي",
    longDescriptionAr: "تنشغل الهيئة بـ 2,100+ شاب سنوياً من خلال تدريب التوظيف والتدريب الداخلي وبرامج القيادة. نتشارك مع أصحاب العمل لوضع الخريجين في وظائف جودة.",
    photo: "",
    gallery: [],
    objectives: ["Train 2,100 youth in job skills", "Achieve 70% employment rate", "Build leadership and civic engagement"],
    objectivesAr: ["تدريب 2,100 شاب على مهارات الوظائف", "تحقيق معدل توظيف 70٪", "بناء القيادة والمشاركة المدنية"],
    status: "Active",
    budget: "$2.0M",
  },
];

export const volunteers = [
  {
    id: "field-medic",
    title: "Field Medic - Gaza",
    slug: "field-medic-gaza",
    location: "Gaza",
    type: "On-site",
    commitment: "Full-time (3+ months)",
    description: "Provide medical support in Gaza emergency response",
    requirements: ["Medical license/certification", "Emergency medicine experience"],
    impact: "Direct medical care to crisis-affected populations",
  },
  {
    id: "clothing-sorter",
    title: "Clothing Bank Sorter",
    slug: "clothing-bank-sorter",
    location: "Jordan (Multiple locations)",
    type: "On-site",
    commitment: "Part-time (4-8 hours/week)",
    description: "Sort, organize, and package clothing donations",
    requirements: ["Physical capability for light lifting"],
    impact: "Help distribute aid to 1000+ families monthly",
  },
  {
    id: "content-creator",
    title: "Remote Content Creator",
    slug: "remote-content-creator",
    location: "Remote",
    type: "Remote",
    commitment: "Part-time (10-15 hours/week)",
    description: "Create social media content and stories about our programs",
    requirements: ["Social media/content creation experience", "Arabic or English fluency"],
    impact: "Reach 100K+ people monthly with our mission",
  },
  {
    id: "tutor",
    title: "Education Tutor",
    slug: "education-tutor",
    location: "Jordan",
    type: "On-site/Hybrid",
    commitment: "Flexible (4+ hours/week)",
    description: "Provide tutoring in Math, Science, or Arabic to underprivileged children",
    requirements: ["Subject matter expertise", "Teaching experience or willingness to learn"],
    impact: "Help 20-30 students improve their academic performance",
  },
  {
    id: "fundraiser",
    title: "Community Fundraiser",
    slug: "community-fundraiser",
    location: "Your Community",
    type: "Remote/On-site",
    commitment: "Flexible (5+ hours/week)",
    description: "Organize fundraising events and campaigns in your community",
    requirements: ["Event planning or organizing experience"],
    impact: "Raise funds for critical humanitarian programs",
  },
  {
    id: "it-support",
    title: "IT Systems Support",
    slug: "it-systems-support",
    location: "Remote",
    type: "Remote",
    commitment: "Part-time (8-12 hours/week)",
    description: "Provide technical support and systems maintenance",
    requirements: ["IT/Systems administration experience"],
    impact: "Keep our digital infrastructure running smoothly",
  },
];

export const news = [
  {
    id: 1,
    title: "Jordan Dispatches Ninth Humanitarian Aid Convoy to Lebanon",
    slug: "ninth-convoy-lebanon",
    date: new Date("2026-06-25"),
    excerpt: "JHCO continues supporting Lebanon with a ninth humanitarian relief convoy",
    titleAr: "الأردن يسيّر القافلة التاسعة من المساعدات الإنسانية إلى لبنان",
    excerptAr: "الهيئة تواصل دعم لبنان الشقيق بقافلة إغاثية جديدة",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image: "",
    category: "Convoys",
  },
  {
    id: 2,
    title: "JHCO and the Bahrain Royal Charity Organisation Sign Cooperation Agreement for Gaza",
    slug: "bahrain-royal-charity-agreement",
    date: new Date("2026-06-25"),
    excerpt: "A new agreement to support those affected in the Gaza Strip",
    titleAr: "الهيئة الخيرية الأردنية الهاشمية والمؤسسة الملكية للأعمال الإنسانية في البحرين توقعان اتفاقية تعاون لدعم المتضررين في قطاع غزة",
    excerptAr: "اتفاقية تعاون جديدة لدعم المتضررين في قطاع غزة",
    content: "The Jordan Hashemite Charity Organization and the Royal Humanitarian Foundation of the Kingdom of Bahrain signed a cooperation agreement aimed at strengthening humanitarian and development efforts to support those affected in the Gaza Strip, through sustainable development, service, and health projects.\n\nThe agreement was signed by JHCO Secretary-General Dr. Hussein Al-Shibli, and by Eng. Ibrahim Hussein Dalhan Al-Dosari, Acting Secretary-General of the Royal Humanitarian Foundation.\n\nThe agreement extends the existing humanitarian partnership between the two sides and establishes an integrated framework for cooperation on housing, education, and health projects in Gaza — including a residential complex, a school, and a health hospital, alongside specialized health programs supporting the wounded, cancer patients, and the provision of prosthetic limbs.\n\nDr. Al-Shibli noted that the agreement represents an important step toward uniting humanitarian efforts and directing them toward quality development projects with long-term impact.",
    contentAr: "وقّعت الهيئة الخيرية الأردنية الهاشمية والمؤسسة الملكية للأعمال الإنسانية في مملكة البحرين اتفاقية تعاون تهدف إلى تعزيز الجهود الإنسانية والتنموية الموجهة لدعم المتضررين في قطاع غزة، من خلال تنفيذ مشاريع تنموية وخدمية وصحية مستدامة تسهم في تحسين الظروف المعيشية وتعزيز قدرة المجتمع على التعافي والاستقرار.\n\nووقع الاتفاقية عن الهيئة الخيرية الأردنية الهاشمية عطوفة الأمين العام الدكتور حسين الشبلي، وعن المؤسسة الملكية للأعمال الإنسانية القائم بأعمال الأمين العام المهندس إبراهيم حسين دلهان الدوسري.\n\nوتأتي هذه الاتفاقية امتدادًا للشراكة الإنسانية القائمة بين الجانبين، وتؤسس لإطار متكامل ينظم التعاون في تنفيذ مشاريع تنموية وخدمية في قطاعات الإسكان والتعليم والصحة، بما يشمل إنشاء مجمع سكني ومدرسة ومستشفى صحي لخدمة المتضررين في قطاع غزة، إلى جانب تنفيذ برامج صحية متخصصة لدعم الجرحى والمصابين ومرضى السرطان وتوفير الأطراف الصناعية.\n\nوأشار الدكتور حسين الشبلي إلى أن هذه الاتفاقية تمثل خطوة مهمة نحو توحيد الجهود الإنسانية وتوجيهها نحو مشاريع تنموية نوعية تحقق أثرًا طويل الأمد.",
    image: "",
    category: "Partnerships",
  },
  {
    id: 3,
    title: "JHCO Concludes \"Ramadan Bel Kheir Ghair\" Campaign Across Jordan and Gaza",
    slug: "ramadan-bel-kheir-ghair",
    date: new Date("2026-06-25"),
    excerpt: "Wide-reaching implementation of the Ramadan campaign in Jordan and the Gaza Strip",
    titleAr: "الهيئة الخيرية الأردنية الهاشمية تختتم حملة \"رمضان بالخير غير\" بتنفيذ واسع في الأردن وقطاع غزة",
    excerptAr: "تنفيذ واسع لحملة رمضان الخيرية في الأردن وقطاع غزة",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image: "",
    category: "Campaigns",
  },
  {
    id: 4,
    title: "Memorandum of Understanding with Nobles Real Estate to Launch University Grants for Underprivileged Students",
    slug: "nobles-university-grants",
    date: new Date("2026-06-25"),
    excerpt: "A new scholarship program for students from families in need",
    titleAr: "مذكرة تفاهم بين الهيئة الخيرية الأردنية الهاشمية ونوبلز العقارية لإطلاق برنامج منح جامعية للطلبة من الأسر العفيفة",
    excerptAr: "برنامج منح جامعية جديد للطلبة من الأسر العفيفة",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image: "",
    category: "Education",
  },
  {
    id: 5,
    title: "Renewed Cooperation to Operate the King Salman Humanitarian Aid Centre's Clinics in Zaatari Camp",
    slug: "king-salman-clinics-zaatari",
    date: new Date("2026-06-25"),
    excerpt: "Continuing joint healthcare operations at Zaatari refugee camp",
    titleAr: "تجديد التعاون في تنفيذ مشروع تشغيل عيادات مركز الملك سلمان للإغاثة والأعمال الإنسانية في مخيم الزعتري",
    excerptAr: "استمرار العمل الصحي المشترك في مخيم الزعتري",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image: "",
    category: "Health",
  },
  {
    id: 6,
    title: "JHCO Begins Manufacturing, Installing, and Distributing Mobile Homes Inside Gaza",
    slug: "mobile-homes-gaza",
    date: new Date("2026-06-25"),
    excerpt: "A new shelter initiative for displaced families inside the Gaza Strip",
    titleAr: "الهيئة الخيرية الأردنية الهاشمية تبدأ تصنيع وتركيب وتوزيع المنازل المتنقلة من داخل قطاع غزة",
    excerptAr: "مبادرة إيواء جديدة للأسر النازحة داخل قطاع غزة",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image: "",
    category: "Shelter",
  },
];

export const countries = [
  // Asia
  { name: "Palestine", nameAr: "فلسطين", region: "asia", featured: true },
  { name: "Syria", nameAr: "سوريا", region: "asia", featured: true },
  { name: "Iraq", nameAr: "العراق", region: "asia", featured: true },
  { name: "Yemen", nameAr: "اليمن", region: "asia", featured: true },
  { name: "Afghanistan", nameAr: "أفغانستان", region: "asia" },
  { name: "Bangladesh", nameAr: "بنغلاديش", region: "asia" },
  { name: "China", nameAr: "الصين", region: "asia" },
  { name: "Georgia", nameAr: "جورجيا", region: "asia" },
  { name: "Indonesia", nameAr: "إندونيسيا", region: "asia" },
  { name: "Iran", nameAr: "إيران", region: "asia" },
  { name: "Japan", nameAr: "اليابان", region: "asia" },
  { name: "Maldives", nameAr: "جزر المالديف", region: "asia" },
  { name: "Pakistan", nameAr: "باكستان", region: "asia" },
  { name: "Philippines", nameAr: "الفلبين", region: "asia" },
  { name: "Sri Lanka", nameAr: "سريلانكا", region: "asia" },
  { name: "Taiwan", nameAr: "تايوان", region: "asia" },
  { name: "Thailand", nameAr: "تايلاند", region: "asia" },
  { name: "Turkey", nameAr: "تركيا", region: "asia" },
  // Africa
  { name: "Egypt", nameAr: "مصر", region: "africa", featured: true },
  { name: "Sudan", nameAr: "السودان", region: "africa", featured: true },
  { name: "Somalia", nameAr: "الصومال", region: "africa" },
  { name: "Morocco", nameAr: "المغرب", region: "africa" },
  { name: "Libya", nameAr: "ليبيا", region: "africa" },
  { name: "Algeria", nameAr: "الجزائر", region: "africa" },
  { name: "Comoros", nameAr: "جزر القمر", region: "africa" },
  { name: "Congo", nameAr: "الكونغو", region: "africa" },
  { name: "Ivory Coast", nameAr: "ساحل العاج", region: "africa" },
  { name: "Liberia", nameAr: "ليبيريا", region: "africa" },
  // Europe
  { name: "Bosnia and Herzegovina", nameAr: "البوسنة والهرسك", region: "europe" },
  { name: "Bulgaria", nameAr: "بلغاريا", region: "europe" },
  { name: "Romania", nameAr: "رومانيا", region: "europe" },
  { name: "North Macedonia", nameAr: "مقدونيا الشمالية", region: "europe" },
  { name: "Abkhazia", nameAr: "أبخازيا", region: "europe" },
  { name: "Chechnya", nameAr: "الشيشان", region: "europe" },
  { name: "South Ossetia", nameAr: "أوسيتيا الجنوبية", region: "europe" },
  // Americas
  { name: "Haiti", nameAr: "هايتي", region: "americas" },
];

export const impactStats = [
  { label: "Families Supported", labelAr: "أسرة مدعومة", value: "75,000+", icon: "👥" },
  { label: "Countries Reached", labelAr: "دولة نصل إليها", value: "30+", icon: "🌍" },
  { label: "Volunteers Active", labelAr: "متطوع نشط", value: "2,500+", icon: "🤝" },
  { label: "Programs Running", labelAr: "برنامجاً قائماً", value: "7+", icon: "📋" },
];

export const teamMembers = [
  { name: "Ahmed Al-Rashid", role: "Executive Director", image: "/team/ahmed.jpg" },
  { name: "Fatima Al-Mansouri", role: "Programs Director", image: "/team/fatima.jpg" },
  { name: "Mohammad Al-Saud", role: "Operations Manager", image: "/team/mohammad.jpg" },
  { name: "Layla Al-Harbi", role: "Finance Director", image: "/team/layla.jpg" },
];

export const donationOptions = [
  {
    amount: 25,
    description: "Feeds one family for a week",
    impact: "Basic meal support",
  },
  {
    amount: 50,
    description: "Medical supplies for 5 families",
    impact: "Healthcare access",
  },
  {
    amount: 100,
    description: "School supplies for 10 children",
    impact: "Educational support",
  },
  {
    amount: 250,
    description: "Vocational training for one person",
    impact: "Skills development",
  },
  {
    amount: 500,
    description: "Medical equipment for clinics",
    impact: "Healthcare infrastructure",
  },
];

// Impact Stories (case studies)
export const impactStories = [
  {
    id: "story-1",
    slug: "amira-gaza-prosthetic",
    title: "Amira's Second Chance: Prosthetic Hope in Gaza",
    titleAr: "فرصة أميرة الثانية: الأمل الصناعي في غزة",
    excerpt: "A 16-year-old lost her leg in the conflict, but found her future through rehabilitation",
    excerptAr: "فتاة في السادسة عشرة فقدت ساقها في الصراع، لكنها وجدت مستقبلها من خلال إعادة التأهيل",
    body: "Amira was just 15 when the conflict began. A month later, a shell struck her home, and she lost her right leg. For six months, she couldn't imagine walking again—until JHCO's Restoring Hope initiative brought her to Jordan for prosthetic fitting. Today, she attends school, helps her family, and mentors other amputees. \"My leg is artificial,\" she says, \"but my dreams are real.\"",
    bodyAr: "كانت أميرة في السادسة عشرة عندما بدأ الصراع. بعد شهر، أصابت قذيفة منزلها، وفقدت ساقها اليمنى. لمدة ستة أشهر، لم تستطع تخيل المشي مجدداً — حتى جلبتها مبادرة استعادة الأمل التابعة للهيئة إلى الأردن لتركيب طرف صناعي. اليوم، تذهب إلى المدرسة، وتساعد عائلتها، وتساعد بتوجيه الآخرين من مبتوري الأطراف.",
    image: "/media/story-amira.jpg",
    category: "Medical Support",
    date: new Date("2025-11-15"),
    featured: true,
  },
  {
    id: "story-2",
    slug: "rafat-clothing-bank-dignity",
    title: "Rafat's Dignity: Shopping with Purpose at the Clothing Bank",
    titleAr: "كرامة رفاعت: التسوق بهدف في بنك الملابس الخيري",
    excerpt: "A family of five found dignity and hope through free clothing and community support",
    excerptAr: "عائلة من خمسة أفراد وجدت الكرامة والأمل من خلال الملابس المجانية والدعم المجتمعي",
    body: "Rafat's father lost his job during the economic downturn, leaving the family without resources. Through the National Aid Fund, they learned about the Clothing Bank. Every member of the family now receives dignified clothing without shame or handouts. \"We're not begging,\" Rafat's mother says. \"We're shopping. That's the difference.\"",
    bodyAr: "فقد والد رفاعت وظيفته خلال الانكماش الاقتصادي، مما ترك الأسرة بدون موارد. من خلال صندوق المساعدة الوطني، تعرفوا على بنك الملابس الخيري. الآن يحصل كل فرد من أفراد الأسرة على ملابس كريمة بدون خجل أو إحسان. \"نحن لا نستعطي،\" تقول والدة رفاعت. \"نحن نتسوق. هذا هو الفرق.\"",
    image: "/media/story-rafat.jpg",
    category: "Basic Needs",
    date: new Date("2025-10-22"),
    featured: true,
  },
  {
    id: "story-3",
    slug: "zahra-education-empowerment",
    title: "Zahra's Dream: From Aid to University",
    titleAr: "حلم زهرة: من المساعدة إلى الجامعة",
    excerpt: "A scholarship helped this young woman become a nurse and give back to her community",
    excerptAr: "منحة دراسية ساعدت هذه الشابة لتصبح ممرضة وتسهم في مجتمعها",
    body: "Zahra's family couldn't afford tuition. JHCO's education support program provided a scholarship for nursing school. Today, Zahra is a registered nurse at a major hospital in Amman, and volunteers monthly at JHCO's clinics. \"I was given a chance,\" she says. \"Now I want to give chances to others.\"",
    bodyAr: "لم تستطع عائلة زهرة تحمل تكاليف الرسوم الدراسية. قدم برنامج دعم التعليم التابع للهيئة منحة دراسية لدراسة التمريض. اليوم، زهرة ممرضة مسجلة في مستشفى كبير في عمّان، وتتطوع شهرياً في عيادات الهيئة.",
    image: "/media/story-zahra.jpg",
    category: "Education",
    date: new Date("2025-09-10"),
    featured: false,
  },
  {
    id: "story-4",
    slug: "mahmoud-orphan-sponsorship",
    title: "Mahmoud's New Family: Orphan Sponsorship Changes Everything",
    titleAr: "عائلة محمود الجديدة: الكفالة تغير كل شيء",
    excerpt: "One sponsor's commitment gave an orphaned boy a future filled with possibility",
    excerptAr: "التزام راعٍ واحد أعطى يتيماً مستقبلاً مليئاً بالإمكانيات",
    body: "Mahmoud was 8 when he lost both parents. For two years, he moved between relatives, never feeling secure. Through JHCO's orphan sponsorship program, a family in Amman became his family. They don't just pay for his schooling—they invite him for holidays, help with homework, and show him he matters. \"I have a family again,\" Mahmoud says quietly.",
    bodyAr: "كان محمود في الثامنة عندما فقد والديه. لمدة سنتين، انتقل بين الأقارب، لا يشعر أبداً بالأمان. من خلال برنامج كفالة الأيتام التابع للهيئة، أصبحت عائلة في عمّان عائلته. لا يقتصر دعمهم على الدفع مقابل تعليمه — بل يدعونه للعطلات، ويساعدونه في الواجبات، ويظهرون له أنه مهم.",
    image: "/media/story-mahmoud.jpg",
    category: "Orphan Support",
    date: new Date("2025-08-05"),
    featured: false,
  },
  {
    id: "story-5",
    slug: "gaza-shelter-camps",
    title: "Hope in Tents: Rebuilding Shelter in Gaza's Camps",
    titleAr: "الأمل في الخيام: إعادة بناء المأوى في مخيمات غزة",
    excerpt: "Families find refuge and stability in dignified shelter provided by JHCO",
    excerptAr: "العائلات تجد الملجأ والاستقرار في المآوي الكريمة التي توفرها الهيئة",
    body: "In the winter of 2026, thousands of families in Gaza faced the harsh elements without shelter. JHCO's emergency shelter program provided weatherproof tents and temporary structures, transforming lives. One family of eight described their tent as 'our first moment of peace since the crisis began.' Today, as JHCO works toward permanent housing, these temporary shelters serve as vital havens for vulnerable families.",
    bodyAr: "في شتاء 2026، واجهت الآلاف من العائلات في غزة قسوة الطبيعة دون مأوى. قدّم برنامج المأوى الطارئ التابع للهيئة خيماً ومنشآت مؤقتة مقاومة للعوامل الجوية، مما غيّر حياة الكثيرين. وصفت إحدى العائلات المكونة من ثمانية أفراد خيمتهم بأنها 'أول لحظة سلام لنا منذ بدء الأزمة.' اليوم، وبينما تعمل الهيئة نحو الإسكان الدائم، تخدم هذه المآوي المؤقتة كملاجئ حيوية للأسر الضعيفة.",
    image: "/media/shelter-camps.jpg",
    category: "Emergency Response",
    date: new Date("2026-07-10"),
    featured: false,
  },
  {
    id: "story-6",
    slug: "gaza-medical-clinic",
    title: "Medicine Without Borders: JHCO's Gaza Medical Clinics",
    titleAr: "الطب بلا حدود: عيادات الهيئة الطبية في غزة",
    excerpt: "Mobile medical clinics bring essential healthcare to isolated communities",
    excerptAr: "العيادات الطبية المتنقلة تجلب الرعاية الصحية الضرورية للمجتمعات المعزولة",
    body: "When traditional infrastructure collapsed, JHCO deployed mobile medical clinics to reach families across Gaza. Dr. Yasmin, a volunteer physician, treats 150 patients daily in areas otherwise cut off from care. 'I came to save lives,' she says, 'and every patient I see reminds me why this work matters.' From vaccinations to emergency trauma care, these clinics are lifelines.",
    bodyAr: "عندما انهار البنية التحتية التقليدية، نشرت الهيئة عيادات طبية متنقلة للوصول إلى العائلات في جميع أنحاء غزة. تعالج الدكتورة ياسمين، طبيبة متطوعة، 150 مريضاً يومياً في مناطق معزولة عن الرعاية. 'جئت لإنقاذ الأرواح،' تقول، 'وكل مريض أراه يذكرني لماذا يهمني هذا العمل.' من التطعيمات إلى الرعاية الطارئة للصدمات، هذه العيادات هي شرايين الحياة.",
    image: "/media/medical-clinic.jpg",
    category: "Medical Support",
    date: new Date("2026-07-08"),
    featured: true,
  },
  {
    id: "story-7",
    slug: "syria-refugee-education",
    title: "From Displacement to Dreams: Syrian Refugee Education",
    titleAr: "من النزوح إلى الأحلام: تعليم اللاجئين السوريين",
    excerpt: "Syrian refugee children regain hope through Tarabot education programs",
    excerptAr: "أطفال اللاجئين السوريين يستعيدون الأمل من خلال برامج ترابط التعليمية",
    body: "Fatima, age 11, fled Syria with her family three years ago. At Tarabot Community Center, she discovered joy in learning again. 'I had forgotten how to smile,' she recalls. 'Now I study, draw, and play with friends.' Through intensive education programs, JHCO helps Syrian refugee children bridge learning gaps and rebuild confidence, opening pathways to brighter futures.",
    bodyAr: "فاطمة، 11 سنة، فرّت من سوريا مع عائلتها قبل ثلاث سنوات. في مركز ترابط المجتمعي، اكتشفت البهجة في التعلم مجدداً. 'كنت قد نسيت كيف أبتسم،' تتذكر. 'الآن أدرس وأرسم والعب مع الأصدقاء.' من خلال برامج التعليم المكثفة، تساعد الهيئة أطفال اللاجئين السوريين على سد فجوات التعلم وإعادة بناء الثقة، مما يفتح طرقاً نحو مستقبل مشرق.",
    image: "/media/refugee-education.jpg",
    category: "Education & Development",
    date: new Date("2026-07-06"),
    featured: false,
  },
  {
    id: "story-8",
    slug: "yemen-water-access",
    title: "Life-Giving Water: Yemen's Water Security Initiative",
    titleAr: "ماء حي: مبادرة الأمن المائي في اليمن",
    excerpt: "Clean water projects transform lives across Yemen's most vulnerable regions",
    excerptAr: "مشاريع المياه النظيفة تحول الحياة في أكثر مناطق اليمن ضعفاً",
    body: "In rural Yemen, families once walked 8 kilometers daily for contaminated water. JHCO's water security project installed 24 wells across three governorates, serving 15,000 people. As one village elder shared, 'Water is more precious than gold to us. Now our children are healthy.' Clean water access has reduced waterborne diseases by 70% and changed childhoods forever.",
    bodyAr: "في اليمن الريفية، كانت العائلات تسير 8 كيلومترات يومياً للحصول على ماء ملوث. نصبت مشاريع الأمن المائي التابعة للهيئة 24 بئراً عبر ثلاث محافظات، تخدم 15,000 شخص. كما قال أحد شيوخ القرى، 'الماء أغلى من الذهب بالنسبة لنا. الآن أطفالنا بصحة جيدة.' حسّن الحصول على ماء نظيف الأمراض المرتبطة بالمياه بنسبة 70٪ وغيّر الطفولة للأبد.",
    image: "/media/yemen-water.jpg",
    category: "Basic Needs",
    date: new Date("2026-07-04"),
    featured: true,
  },
  {
    id: "story-9",
    slug: "lebanon-livelihood",
    title: "Rebuilding Futures: Livelihood Programs in Lebanon",
    titleAr: "إعادة بناء المستقبل: برامج سبل العيش في لبنان",
    excerpt: "Economic empowerment helps Lebanese families regain independence",
    excerptAr: "التمكين الاقتصادي يساعد العائلات اللبنانية على استعادة الاستقلالية",
    body: "When Lebanon's economy collapsed, Ahmed, a carpenter, had no work. JHCO's livelihood program provided microfinance and business training. Within six months, he opened his own small workshop. 'I thought my life was over,' he says, 'but JHCO gave me tools and hope to rebuild.' Today, Ahmed employs three others, creating a ripple of prosperity in his community.",
    bodyAr: "عندما انهار الاقتصاد اللبناني، لم يكن لدى أحمد، نجار، أي عمل. قدّم برنامج سبل العيش التابع للهيئة تمويلاً أصغر وتدريباً على الأعمال. في غضون ستة أشهر، فتح ورشته الخاصة. 'ظننت أن حياتي انتهت،' يقول، 'لكن الهيئة أعطتني أدوات وأملاً لإعادة البناء.' اليوم، يوظف أحمد ثلاثة آخرين، مما ينشئ موجة ازدهار في مجتمعه.",
    image: "/media/lebanon-livelihood.jpg",
    category: "Livelihood",
    date: new Date("2026-07-02"),
    featured: false,
  },
  {
    id: "story-10",
    slug: "palestine-mental-health",
    title: "Healing Hearts: Mental Health Support in Palestine",
    titleAr: "شفاء القلوب: الدعم النفسي في فلسطين",
    excerpt: "Psychosocial support helps trauma survivors rebuild emotional resilience",
    excerptAr: "الدعم النفسي الاجتماعي يساعد ضحايا الصدمات على إعادة بناء الصمود العاطفي",
    body: "Trauma runs deep in Palestine. JHCO's psychosocial support program offers safe spaces where survivors share, heal, and rebuild. Counselor Layla works with children who have witnessed violence. 'I teach them that their pain is valid, and their recovery is possible,' she explains. Through group therapy, art, and music, hundreds are finding paths to emotional stability.",
    bodyAr: "الصدمة تتجذر بعمق في فلسطين. يقدّم برنامج الدعم النفسي الاجتماعي التابع للهيئة أماكن آمنة حيث يتشارك الناجون ويشفون وينعمون. تعمل المستشارة ليلى مع أطفال شهدوا عنفاً. 'أعلمهم أن ألمهم حقيقي، وتعافيهم ممكن،' تشرح. من خلال العلاج الجماعي والفن والموسيقى، يجد المئات طرقاً نحو الاستقرار العاطفي.",
    image: "/media/palestine-mental-health.jpg",
    category: "Psychosocial Support",
    date: new Date("2026-06-30"),
    featured: true,
  },
  {
    id: "story-11",
    slug: "sudan-emergency",
    title: "Standing Strong: Emergency Response in Sudan",
    titleAr: "الوقوف بقوة: الاستجابة الطارئة في السودان",
    excerpt: "JHCO's rapid emergency protocols save lives during humanitarian crises",
    excerptAr: "البروتوكولات الطارئة السريعة للهيئة تنقذ الأرواح أثناء الأزمات الإنسانية",
    body: "When conflict erupted in Sudan, JHCO mobilized within hours. Food parcels, medicine, and shelter reached isolated communities within days. Program director Hassan coordinated relief across three states. 'Our network and protocols meant we could act faster than the crisis spread,' he says. This rapid response saved thousands of lives and set a model for humanitarian intervention.",
    bodyAr: "عندما اندلع الصراع في السودان، تحركت الهيئة في غضون ساعات. وصلت السلال الغذائية والدواء والمأوى للمجتمعات المعزولة في غضون أيام. نسق مدير البرنامج حسن الإغاثة عبر ثلاث ولايات. 'شبكتنا والبروتوكولات لدينا تعني أننا استطعنا التحرك أسرع من انتشار الأزمة،' يقول. نقذت هذه الاستجابة السريعة آلاف الأرواح وحددت نموذجاً للتدخل الإنساني.",
    image: "/media/sudan-emergency.jpg",
    category: "Emergency Response",
    date: new Date("2026-06-28"),
    featured: false,
  },
  {
    id: "story-12",
    slug: "child-sponsorship-story",
    title: "One Child, One Future: The Power of Sponsorship",
    titleAr: "طفل واحد، مستقبل واحد: قوة الكفالة",
    excerpt: "Individual sponsorships transform the lives of vulnerable children",
    excerptAr: "الكفالات الفردية تحول حياة الأطفال الضعفاء",
    body: "Karim was an orphan with no prospects. When a sponsor from Jordan committed to his education, everything changed. He attended school regularly, received health care, and gained mentorship. Today, Karim is 18 and pursuing engineering studies. 'My sponsor gave me more than money,' he says. 'They gave me belief in myself.' Child sponsorship programs create lasting bonds and open life-changing opportunities.",
    bodyAr: "كان كريم يتيماً بدون آفاق. عندما التزم راعٍ من الأردن بتعليمه، تغيّر كل شيء. التحق بالمدرسة بانتظام، وحصل على الرعاية الصحية، واكتسب التوجيه. اليوم، كريم في سن 18 وسعيد لدراسة الهندسة. 'أعطاني راعيتي أكثر من المال،' يقول. 'أعطوني الإيمان بنفسي.' تنشئ برامج كفالة الأطفال روابط دائمة وتفتح فرصاً تغيّر الحياة.",
    image: "/media/child-sponsor.jpg",
    category: "Education & Development",
    date: new Date("2026-06-26"),
    featured: true,
  },
  {
    id: "story-13",
    slug: "women-empowerment",
    title: "From Survival to Success: Women Entrepreneurs",
    titleAr: "من البقاء إلى النجاح: رائدات الأعمال",
    excerpt: "Women entrepreneurs build sustainable futures through JHCO support",
    excerptAr: "رائدات الأعمال يبنين مستقبلاً مستداماً من خلال دعم الهيئة",
    body: "Amina was a widow with three children and no skills. JHCO's Arzaq program trained her in textile production and provided microfinance. She now employs five women and earns enough to send her children to university. 'I went from begging for work to creating work for others,' she says proudly. Women empowerment programs create multiplier effects across communities.",
    bodyAr: "كانت أمينة أرملة لديها ثلاثة أطفال وبدون مهارات. أعدّها برنامج أرزاق التابع للهيئة في إنتاج النسيج ووفّر لها تمويلاً أصغر. تعمل الآن بتوظيف خمس نساء وتكسب ما يكفي لإرسال أطفالها للجامعة. 'ذهبت من التسول من أجل العمل إلى خلق فرص عمل للآخرين،' تقول بفخر. تنشئ برامج تمكين المرأة تأثيرات مضاعفة عبر المجتمعات.",
    image: "/media/women-entrepreneur.jpg",
    category: "Economic Empowerment",
    date: new Date("2026-06-24"),
    featured: false,
  },
  {
    id: "story-14",
    slug: "elderly-care",
    title: "Dignity in Age: Comprehensive Elderly Care",
    titleAr: "الكرامة في الشيخوخة: الرعاية الشاملة للمسنين",
    excerpt: "Elderly care programs ensure seniors live with respect and support",
    excerptAr: "برامج رعاية المسنين تضمن أن يعيش كبار السن بالاحترام والدعم",
    body: "Abu Khalil, 79, lost his wife and lived alone. JHCO's elderly care program paired him with volunteers, provided monthly medical check-ups, and delivered nutritious meals. 'People visit me now,' he shares. 'I'm not forgotten.' Beyond physical care, elderly support programs address isolation and dignity—ensuring sunset years are marked by community, purpose, and joy.",
    bodyAr: "أبو خليل، 79 سنة، فقد زوجته وعاش وحيداً. ربطه برنامج رعاية المسنين التابع للهيئة بمتطوعين، وقدّم له فحوصات طبية شهرية، وسلّم وجبات غذائية مغذية. 'الناس تزورني الآن،' يشارك. 'لم أكن منسياً.' فوق الرعاية الجسدية، تعالج برامج دعم المسنين العزلة والكرامة — مما يضمن أن تتميز السنوات الأخيرة بالمجتمع والغرض والفرح.",
    image: "/media/elderly-care.jpg",
    category: "Basic Needs",
    date: new Date("2026-06-22"),
    featured: true,
  },
  {
    id: "story-15",
    slug: "amputee-rehabilitation",
    title: "Restoring Mobility: Amputee Rehabilitation Success",
    titleAr: "استعادة الحركة: نجاح تأهيل مبتوري الأطراف",
    excerpt: "Advanced rehabilitation gives amputees independence and hope",
    excerptAr: "إعادة تأهيل متقدمة تعطي مبتوري الأطراف استقلالية وأملاً",
    body: "Mohammed, an amputee, thought his life was over. JHCO's Restoring Hope program fitted him with a prosthetic limb and enrolled him in rehabilitation. Within months, he walked, then ran, then returned to work as a teacher. 'My students were shocked when I ran across the classroom,' he laughs. 'But that's the point—I'm fully alive again.' Rehabilitation transforms loss into new beginnings.",
    bodyAr: "محمد، مبتور طرف، ظنّ أن حياته انتهت. زوّده برنامج استعادة الأمل التابع للهيئة بطرف صناعي والتحق في إعادة التأهيل. في غضون أشهر، مشى، ثم ركض، ثم عاد للعمل معلماً. 'تفاجأ طلابي عندما ركضت عبر الفصول،' يضحك. 'لكن هذه هي الفكرة — أنا على قيد الحياة مجدداً.' تحول إعادة التأهيل الفقدان إلى بدايات جديدة.",
    image: "/media/amputee-rehab.jpg",
    category: "Medical Support",
    date: new Date("2026-06-20"),
    featured: false,
  },
  {
    id: "story-16",
    slug: "education-transformation",
    title: "Breaking Barriers: Education Transformation Programs",
    titleAr: "كسر الحواجز: برامج تحويل التعليم",
    excerpt: "Education programs unlock potential in underserved communities",
    excerptAr: "برامج التعليم تفتح الإمكانيات في المجتمعات المحرومة",
    body: "Hana lived in a remote area with no access to quality education. JHCO's education program brought tutors to her village and provided scholarships. From struggling in elementary to excelling in high school, Hana's journey inspired her entire community. 'Education isn't a luxury,' she tells younger children. 'It's a right. And when you have access, you fly.' Education transformation creates generations of opportunity.",
    bodyAr: "عاشت هناء في منطقة نائية بدون إمكانية الوصول إلى تعليم جودة. أحضر برنامج التعليم التابع للهيئة معلمين إلى قريتها ووفّر منحاً. من النضال في الابتدائية إلى التفوق في الثانوية، ألهمت رحلة هناء المجتمع بأكمله. 'التعليم ليس ترفاً،' تخبر الأطفال الأصغر. 'إنه حق. وعندما يكون لديك الوصول، أنت تطير.' تنشئ تحويلات التعليم أجيالاً من الفرص.",
    image: "/media/education-transform.jpg",
    category: "Education & Development",
    date: new Date("2026-06-18"),
    featured: true,
  },
  {
    id: "story-17",
    slug: "livelihood-success",
    title: "Crafting Futures: Livelihood Program Success Stories",
    titleAr: "حرفة المستقبل: قصص نجاح برامج سبل العيش",
    excerpt: "Vocational training and microfinance create lasting economic independence",
    excerptAr: "التدريب المهني والتمويل الأصغر ينشئان استقلالية اقتصادية دائمة",
    body: "Zainab learned pottery through JHCO's vocational training and started selling at Dhii showroom. Today, her handmade ceramics are sought after by collectors. 'I never imagined I'd be this successful,' she says. 'But with training and a platform to sell, dreams became real.' Livelihood programs transform skills into sustainable income and community pride.",
    bodyAr: "تعلمت زينب الفخار من خلال التدريب المهني التابع للهيئة وبدأت البيع في معرض ضي. اليوم، منتجاتها الخزفية اليدوية مطلوبة من قبل الجامعين. 'لم أتخيل أنني سأكون هكذا ناجحة،' تقول. 'لكن مع التدريب ومنصة للبيع، أصبحت الأحلام حقيقية.' تحول برامج سبل العيش المهارات إلى دخل مستدام وفخر مجتمعي.",
    image: "/media/livelihood-success.jpg",
    category: "Economic Empowerment",
    date: new Date("2026-06-16"),
    featured: false,
  },
  {
    id: "story-18",
    slug: "health-transformation",
    title: "Health for All: Transformation Through Healthcare",
    titleAr: "الصحة للجميع: التحول من خلال الرعاية الصحية",
    excerpt: "Healthcare access transforms health outcomes and quality of life",
    excerptAr: "الحصول على الرعاية الصحية يحول النتائج الصحية وجودة الحياة",
    body: "In a rural clinic supported by JHCO, mothers now have safe places to give birth and children receive vaccines. Noor, a nurse, works in a region where maternal mortality was once high. 'Every birth I attend, every vaccine administered, is a life protected,' she says. Healthcare programs don't just treat illness—they build healthier, stronger communities.",
    bodyAr: "في عيادة ريفية يدعمها الهيئة، لدى الأمهات الآن أماكن آمنة للولادة ويحصل الأطفال على التطعيمات. تعمل نور، ممرضة، في منطقة كانت الوفيات الأمومية فيها مرتفعة. 'كل ولادة أحضرها، كل لقاح أعطيه، هو حياة محمية،' تقول. لا تعالج برامج الرعاية الصحية المرض فقط — فهي تبني مجتمعات أصحّ وأقوى.",
    image: "/media/health-transform.jpg",
    category: "Medical Support",
    date: new Date("2026-06-14"),
    featured: true,
  },
  {
    id: "story-19",
    slug: "community-resilience",
    title: "Unity in Crisis: Building Community Resilience",
    titleAr: "الوحدة في الأزمة: بناء صمود المجتمع",
    excerpt: "Community programs strengthen social bonds and collective resilience",
    excerptAr: "برامج المجتمع تقوي الروابط الاجتماعية والصمود الجماعي",
    body: "When crisis hit, JHCO's community centers became safe havens where neighbors connected and supported each other. In one center, volunteers organized group cooking, children's activities, and mental health support. As one participant said, 'We realized we weren't alone in our struggle. Together, we're stronger.' Community resilience programs transform individual challenges into collective strength.",
    bodyAr: "عندما ضربت الأزمة، أصبحت مراكز المجتمع التابعة للهيئة ملاجئ آمنة حيث تواصل الجيران ودعم بعضهم. في أحد المراكز، نظّم المتطوعون طهياً جماعياً وأنشطة للأطفال ودعماً نفسياً. كما قال أحد المشاركين، 'أدركنا أننا لسنا وحدنا في النضال. معاً، نحن أقوى.' تحول برامج صمود المجتمع التحديات الفردية إلى قوة جماعية.",
    image: "/media/community-resilience.jpg",
    category: "Community Development",
    date: new Date("2026-06-12"),
    featured: false,
  },
];

// Events & Campaigns Calendar
export const events = [
  {
    id: "event-1",
    title: "Ramadan Aid Campaign 2026",
    titleAr: "حملة رمضان 2026",
    slug: "ramadan-aid-2026",
    date: new Date("2026-02-25"),
    endDate: new Date("2026-03-25"),
    type: "Campaign",
    description: "Special month of giving: 30-day campaign providing meals, food packages, and essential aid",
    descriptionAr: "شهر العطاء الخاص: حملة مدتها 30 يوماً توفر الوجبات والطرود الغذائية والمساعدات الأساسية",
    link: "/campaigns/ramadan-2026",
    featured: true,
  },
  {
    id: "event-2",
    title: "Back to School Drive",
    titleAr: "حملة العودة للمدارس",
    slug: "back-to-school-2025",
    date: new Date("2025-08-15"),
    endDate: new Date("2025-09-15"),
    type: "Campaign",
    description: "Providing school supplies, uniforms, and bags to students in need",
    descriptionAr: "توفير أدوات مدرسية وزي موحد وحقائب للطلاب المحتاجين",
    link: "/campaigns/back-to-school-2025",
    featured: true,
  },
  {
    id: "event-3",
    title: "Charity Gala Dinner & Auction",
    titleAr: "حفل عشاء خيري ومزاد",
    slug: "gala-dinner-2025",
    date: new Date("2025-12-10"),
    type: "Fundraiser",
    description: "Annual charity gala in Amman with live auction, entertainment, and networking",
    descriptionAr: "حفل خيري سنوي في عمّان مع مزاد مباشر وترفيه وتواصل",
    link: "/events/gala-dinner-2025",
    featured: false,
  },
  {
    id: "event-4",
    title: "Volunteer Appreciation Day",
    titleAr: "يوم تقدير المتطوعين",
    slug: "volunteer-day-2025",
    date: new Date("2025-12-05"),
    type: "Event",
    description: "Celebrating our 2,800+ volunteers with recognition, training, and community building",
    descriptionAr: "الاحتفال بأكثر من 2,800 متطوع لدينا بالتقدير والتدريب وبناء المجتمع",
    link: "/events/volunteer-day-2025",
    featured: false,
  },
];

// Job Listings
export const jobs = [
  {
    id: "job-1",
    title: "Program Manager - Gaza Crisis Response",
    titleAr: "مدير برنامج - الاستجابة لأزمة غزة",
    slug: "program-manager-gaza",
    location: "Amman, Jordan",
    locationAr: "عمّان، الأردن",
    department: "Emergency Response",
    departmentAr: "الاستجابة الطارئة",
    description: "Lead coordination of aid delivery to Gaza through our air and land bridges. Manage partnerships with international agencies, oversee logistics, and ensure beneficiary impact tracking.",
    descriptionAr: "قيادة تنسيق إيصال المساعدات إلى غزة من خلال جسورنا الجوية والبرية. إدارة الشراكات مع الوكالات الدولية، والإشراف على اللوجستيات، وضمان تتبع تأثير المستفيدين.",
    type: "Full-time",
    salary: "$50K - $65K/year",
    posted: new Date("2025-11-01"),
    featured: true,
  },
  {
    id: "job-2",
    title: "Communications Officer - English",
    titleAr: "ضابط اتصالات - اللغة الإنجليزية",
    slug: "communications-officer",
    location: "Amman, Jordan",
    locationAr: "عمّان، الأردن",
    department: "Communications & Advocacy",
    departmentAr: "الاتصالات والمناصرة",
    description: "Tell JHCO's impact stories to the world. Write newsletters, manage social media, coordinate press releases, and develop multimedia content for international audiences.",
    descriptionAr: "حكي قصص تأثير الهيئة للعالم. كتابة النشرات الإخبارية، وإدارة وسائل التواصل الاجتماعي، وتنسيق البيانات الصحفية، وتطوير محتوى متعدد الوسائط للجماهير الدولية.",
    type: "Full-time",
    salary: "$35K - $45K/year",
    posted: new Date("2025-10-15"),
    featured: false,
  },
  {
    id: "job-3",
    title: "Volunteer Coordinator",
    titleAr: "منسق المتطوعين",
    slug: "volunteer-coordinator",
    location: "Amman, Jordan",
    locationAr: "عمّان، الأردن",
    department: "Volunteer Services",
    departmentAr: "خدمات التطوع",
    description: "Recruit, train, and manage our growing volunteer network. Coordinate placements, track hours, organize volunteer events, and develop retention strategies.",
    descriptionAr: "تجنيد وتدريب وإدارة شبكة المتطوعين المتنامية لدينا. تنسيق التوظيفات، وتتبع الساعات، وتنظيم فعاليات المتطوعين، وتطوير استراتيجيات الاحتفاظ.",
    type: "Full-time",
    salary: "$28K - $38K/year",
    posted: new Date("2025-10-20"),
    featured: false,
  },
];

// Locations / Branches Directory
export const locations = [
  {
    id: "loc-head",
    name: "Head Office",
    nameAr: "المقر الرئيسي",
    slug: "head-office",
    city: "Amman",
    cityAr: "عمّان",
    address: "Al-Mahatta District, Amman",
    addressAr: "منطقة المحطة، عمّان",
    phone: "+962-6-568-7777",
    email: "info@jhco.org.jo",
    hours: "8 AM - 4 PM, Sat-Thu",
    hoursAr: "8 صباحاً - 4 مساءً، السبت-الخميس",
    description: "Main administrative office and headquarters",
    descriptionAr: "المكتب الإداري الرئيسي ومقر الهيئة",
  },
  {
    id: "loc-clothing-bank",
    name: "Charity Clothing Bank Exhibition",
    nameAr: "معرض بنك الملابس الخيري",
    slug: "clothing-bank-main",
    city: "Amman",
    cityAr: "عمّان",
    address: "Al-Mahatta District, next to Head Office",
    addressAr: "منطقة المحطة، بجانب المقر الرئيسي",
    phone: "+962-6-568-8888",
    email: "clothing@jhco.org.jo",
    hours: "9 AM - 3 PM, Sat-Thu",
    hoursAr: "9 صباحاً - 3 مساءً، السبت-الخميس",
    description: "Main showroom where beneficiary families shop for free clothing",
    descriptionAr: "غرفة العرض الرئيسية حيث تتسوق الأسر المستفيدة للملابس المجانية",
  },
  {
    id: "loc-mafraq",
    name: "Mafraq Warehouse",
    nameAr: "مستودع المفرق",
    slug: "mafraq-warehouse",
    city: "Mafraq",
    cityAr: "المفرق",
    address: "Industrial Zone, Mafraq",
    addressAr: "المنطقة الصناعية، المفرق",
    phone: "+962-2-629-9999",
    description: "Storage and distribution center for northern region aid operations",
    descriptionAr: "مركز التخزين والتوزيع لعمليات المساعدات في المنطقة الشمالية",
  },
  {
    id: "loc-ghabawi",
    name: "Ghabawi Warehouse & Sorting Center",
    nameAr: "مستودع ومركز فرز الغبيري",
    slug: "ghabawi-warehouse",
    city: "Amman",
    cityAr: "عمّان",
    address: "Ghabawi Area, Amman",
    addressAr: "منطقة الغبيري، عمّان",
    phone: "+962-6-780-0000",
    description: "Main distribution hub for clothing and relief supplies",
    descriptionAr: "مركز التوزيع الرئيسي للملابس والإمدادات الإغاثية",
  },
];

// Crisis Response Pages
export const crisisPages = [
  {
    id: "crisis-gaza",
    title: "Gaza Crisis Response",
    titleAr: "الاستجابة لأزمة غزة",
    slug: "gaza-crisis",
    country: "Palestine (Gaza Strip)",
    countryAr: "فلسطين (قطاع غزة)",
    status: "Active Emergency",
    statusAr: "حالة طارئة نشطة",
    overview: "Since 2023, JHCO has coordinated a major humanitarian response to the Gaza crisis. Operating an air bridge from Marka Airport, managing land convoys, and implementing on-ground projects including food distribution, medical care, shelter, and psychosocial support.",
    overviewAr: "منذ عام 2023، نسقت الهيئة استجابة إنسانية كبيرة لأزمة غزة. تشغيل جسر جوي من مطار ماركا، وإدارة قوافل برية، وتنفيذ مشاريع على الأرض تشمل توزيع الغذاء والرعاية الطبية والمأوى والدعم النفسي الاجتماعي.",
    initiatives: ["For Our People in Gaza", "Restoring Hope (Amputees)", "Emergency Healthcare", "Shelter & Supplies"],
    initiativesAr: ["حملة لأهلنا في غزة", "استعادة الأمل (مبتورو الأطراف)", "الرعاية الصحية الطارئة", "المأوى والإمدادات"],
    image: "/media/crisis-gaza.jpg",
  },
  {
    id: "crisis-syria",
    title: "Syria Humanitarian Response",
    titleAr: "الاستجابة الإنسانية لسوريا",
    slug: "syria-crisis",
    country: "Syria",
    countryAr: "سوريا",
    status: "Ongoing Support",
    statusAr: "دعم مستمر",
    overview: "JHCO operates in Syria supporting internally displaced persons, providing food, medicine, and shelter across multiple governorates. Partnerships with local organizations ensure culturally sensitive, community-driven assistance.",
    overviewAr: "تعمل الهيئة في سوريا لدعم النازحين داخلياً، وتوفير الغذاء والدواء والمأوى عبر عدة محافظات. تضمن الشراكات مع المنظمات المحلية المساعدة الحساسة ثقافياً والمدفوعة بالمجتمع.",
    initiatives: ["Food & Medicine Distribution", "Shelter Projects", "Education Support", "WASH (Water & Sanitation)"],
    initiativesAr: ["توزيع الغذاء والدواء", "مشاريع المأوى", "دعم التعليم", "المياه والصرف الصحي"],
    image: "/media/crisis-syria.jpg",
  },
  {
    id: "crisis-yemen",
    title: "Yemen Emergency Response",
    titleAr: "الاستجابة الطارئة لليمن",
    slug: "yemen-crisis",
    country: "Yemen",
    countryAr: "اليمن",
    status: "Active Emergency",
    statusAr: "حالة طارئة نشطة",
    overview: "Coordinating humanitarian aid across Yemen's northern and southern regions, focusing on health interventions, food security, and malnutrition prevention in collaboration with UN agencies.",
    overviewAr: "تنسيق المساعدات الإنسانية عبر المناطق الشمالية والجنوبية في اليمن، مع التركيز على التدخلات الصحية والأمن الغذائي والوقاية من سوء التغذية بالتعاون مع وكالات الأمم المتحدة.",
    initiatives: ["Healthcare Programs", "Food Security", "Nutrition Centers", "WASH"],
    initiativesAr: ["برامج الرعاية الصحية", "الأمن الغذائي", "مراكز التغذية", "المياه والصرف الصحي"],
    image: "/media/crisis-yemen.jpg",
  },
];

// Gift Marketplace
export const giftItems = [
  {
    id: "gift-1",
    name: "School Starter Kit",
    nameAr: "مجموعة بدء الدراسة",
    slug: "school-starter-kit",
    price: 25,
    description: "Provides school supplies for one child: notebooks, pens, erasers, ruler, and backpack",
    descriptionAr: "يوفر أدوات مدرسية لطفل واحد: دفاتر وأقلام وممحاة ومسطرة وحقيبة",
    image: "/media/gift-school.jpg",
  },
  {
    id: "gift-2",
    name: "Warm Winter Package",
    nameAr: "حزمة الشتاء الدافئة",
    slug: "winter-package",
    price: 50,
    description: "Provides winter clothing, blankets, and heating supplies for one family",
    descriptionAr: "يوفر ملابس شتوية وبطانيات وإمدادات تدفئة لعائلة واحدة",
    image: "/media/gift-winter.jpg",
  },
  {
    id: "gift-3",
    name: "Food Basket",
    nameAr: "سلة الغذاء",
    slug: "food-basket",
    price: 35,
    description: "Monthly food supplies including rice, oil, flour, and canned goods",
    descriptionAr: "إمدادات غذائية شهرية تشمل الأرز والزيت والدقيق والمعلبات",
    image: "/media/gift-food.jpg",
  },
  {
    id: "gift-4",
    name: "Health Clinic Care",
    nameAr: "رعاية العيادة الصحية",
    slug: "health-clinic-care",
    price: 75,
    description: "Provides medical consultations, basic treatments, and medications for 50 patients",
    descriptionAr: "يوفر الاستشارات الطبية والعلاجات الأساسية والأدوية لـ 50 مريضاً",
    image: "/media/gift-health.jpg",
  },
  {
    id: "gift-5",
    name: "Prosthetic Hope",
    nameAr: "الأمل الصناعي",
    slug: "prosthetic-hope",
    price: 1500,
    description: "Contributes toward prosthetic limb fitting and rehabilitation for an amputee",
    descriptionAr: "يساهم في تركيب طرف صناعي وإعادة تأهيل مبتور طرف",
    image: "/media/gift-prosthetic.jpg",
  },
];

// Student Chapters
export const studentChapters = [
  {
    id: "chapter-ju",
    name: "Jordan University Chapter",
    nameAr: "فصل الجامعة الأردنية",
    slug: "jordan-university",
    university: "Jordan University",
    universityAr: "الجامعة الأردنية",
    city: "Amman",
    cityAr: "عمّان",
    president: "Nada Al-Rasheed",
    presidentAr: "ندى الرشيد",
    members: 150,
    activities: "Monthly volunteer drives, awareness campaigns, fundraising events",
    activitiesAr: "محاولات تطوع شهرية وحملات توعية وفعاليات جمع التبرعات",
  },
  {
    id: "chapter-asu",
    name: "Al-Zaytoonah University Chapter",
    nameAr: "فصل جامعة الزيتونة",
    slug: "zaytoonah-university",
    university: "Al-Zaytoonah University",
    universityAr: "جامعة الزيتونة الأردنية",
    city: "Amman",
    cityAr: "عمّان",
    president: "Ahmed Al-Khatib",
    presidentAr: "أحمد الخطيب",
    members: 120,
    activities: "Clothing bank volunteering, international outreach, skill-sharing workshops",
    activitiesAr: "تطوع بنك الملابس والتواصل الدولي وورش عمل تبادل المهارات",
  },
];

// Corporate Partnership Tiers
export const corporateTiers = [
  {
    id: "tier-bronze",
    name: "Bronze Partner",
    nameAr: "شريك برونزي",
    level: "Bronze",
    minAnnual: 10000,
    benefits: ["Logo on website", "Quarterly newsletter mention", "Certificate of partnership", "Tax deduction"],
    benefitsAr: ["شعار على الموقع", "ذكر في النشرة الفصلية", "شهادة شراكة", "خصم ضريبي"],
  },
  {
    id: "tier-silver",
    name: "Silver Partner",
    nameAr: "شريك فضي",
    level: "Silver",
    minAnnual: 25000,
    benefits: ["Bronze benefits", "Co-branding opportunity", "Monthly newsletter feature", "Dedicated partnership manager", "Employee volunteer day"],
    benefitsAr: ["مزايا برونزية", "فرصة العلامات المشتركة", "ميزة النشرة الشهرية", "مدير شراكة مخصص", "يوم تطوع الموظفين"],
  },
  {
    id: "tier-gold",
    name: "Gold Partner",
    nameAr: "شريك ذهبي",
    level: "Gold",
    minAnnual: 50000,
    benefits: ["Silver benefits", "Custom program sponsorship", "Bi-monthly impact reports", "Executive networking events", "Custom press release"],
    benefitsAr: ["مزايا فضية", "رعاية برنامج مخصصة", "تقارير التأثير كل شهرين", "فعاليات التواصل التنفيذي", "بيان صحفي مخصص"],
  },
  {
    id: "tier-platinum",
    name: "Platinum Partner",
    nameAr: "شريك بلاتيني",
    level: "Platinum",
    minAnnual: 100000,
    benefits: ["Gold benefits", "Major program naming rights", "Quarterly board briefing", "Leadership council seat", "Custom impact study"],
    benefitsAr: ["مزايا ذهبية", "حقوق تسمية البرنامج الرئيسي", "إحاطة مجلس الإدارة الفصلية", "مقعد مجلس القيادة", "دراسة تأثير مخصصة"],
  },
];

export const clothingBankBranches = [
  {
    id: "branch-1",
    name: "Main Exhibition - Al-Mahatta",
    nameAr: "المعرض الرئيسي - المحطة",
    slug: "clothing-bank-main",
    address: "Al-Mahatta District, Amman",
    addressAr: "منطقة المحطة، عمّان",
    phone: "+962-6-568-8888",
    hours: "9 AM - 3 PM, Sat-Thu",
    description: "Main shopping venue for registered families",
    descriptionAr: "مقر التسوق الرئيسي للأسر المسجلة",
    capacity: 500,
  },
];

export const tarabot = {
  name: "Tarabot Project",
  nameAr: "مشروع طرابوط",
  description: "Mental health support and life skills training for youth in crisis situations",
  descriptionAr: "دعم الصحة النفسية وتدريب مهارات الحياة للشباب في حالات الأزمات",
  phone: "+962-6-123-4567",
  email: "tarabot@jhco.org.jo",
  schedule: "Fixed activities and therapeutic sessions available - see PDF schedule",
  scheduleAr: "الأنشطة الثابتة وجلسات العلاج متاحة - انظر جدول PDF",
  schedulePDF: "/reports/tarabot-schedule.pdf",
  contact: "Call or email to register. Walk-ins welcome on specific days.",
  contactAr: "اتصل أو أرسل بريداً إلكترونياً للتسجيل. الزوار الجدد مرحب بهم في أيام محددة.",
};

// Local & International Partners
export const localPartners = [
  { id: 1, name: "Ministry of Health", nameAr: "وزارة الصحة" },
  { id: 2, name: "Ministry of Social Development", nameAr: "وزارة التنمية الاجتماعية" },
  { id: 3, name: "Jordanian Red Crescent", nameAr: "الهلال الأحمر الأردني" },
  { id: 4, name: "Al-Aman Fund", nameAr: "صندوق الأمان" },
  { id: 5, name: "Islamic Action Front", nameAr: "جبهة العمل الإسلامي" },
  { id: 6, name: "Women's Union of Jordan", nameAr: "اتحاد نساء الأردن" },
  { id: 7, name: "Jordan Youth Association", nameAr: "جمعية الشباب الأردنية" },
  { id: 8, name: "Amman Municipality", nameAr: "أمانة عمّان الكبرى" },
  { id: 9, name: "National Aid Fund", nameAr: "صندوق المساعدة الوطني" },
  { id: 10, name: "Jordan Media Institute", nameAr: "معهد الإعلام الأردني" },
  { id: 11, name: "Caritas Jordan", nameAr: "كاريتاس الأردن" },
  { id: 12, name: "Jordanian Engineers Association", nameAr: "جمعية المهندسين الأردنيين" },
];

export const internationalPartners = [
  { id: 1, name: "World Health Organization", nameAr: "منظمة الصحة العالمية" },
  { id: 2, name: "UNICEF", nameAr: "يونيسيف" },
  { id: 3, name: "UN Women", nameAr: "هيئة الأمم المتحدة للمرأة" },
  { id: 4, name: "World Food Programme", nameAr: "برنامج الغذاء العالمي" },
  { id: 5, name: "UNHCR", nameAr: "مفوضية الأمم المتحدة لشؤون اللاجئين" },
  { id: 6, name: "International Red Cross", nameAr: "الصليب الأحمر الدولي" },
  { id: 7, name: "Islamic Relief Worldwide", nameAr: "جمعية الإغاثة الإسلامية العالمية" },
  { id: 8, name: "Human Appeal", nameAr: "نداء الإنسانية" },
  { id: 9, name: "Médecins Sans Frontières", nameAr: "أطباء بلا حدود" },
  { id: 10, name: "Oxfam", nameAr: "أوكسفام" },
  { id: 11, name: "Save the Children", nameAr: "أنقذوا الأطفال" },
  { id: 12, name: "World Vision", nameAr: "رؤية العالم" },
];
